spring:
 profiles.active: development

---
spring:
  profiles: development
#  mvc:  
    #view:
    #  prefix: /WEB-INF/jsp/
    #  suffix: .jsp
  datasource:
      url: jdbc:mariadb://127.0.0.1:3306/iron_shutter_db
      username: iron_shutter_dba
      password: rlaehdgus123
      driver-class-name: org.mariadb.jdbc.Driver
      driverClassName: org.mariadb.jdbc.Driver
      tomcat:
        min-idle: 5
        #initial-size: 5 
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    #password: gksdkfkd123
    port: 6379
  servlet:
    multipart:
      #multipart file size limitation
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    org:
      springframework:
        web: DEBUG
server:
  port: 8080

